FROM node:16.14.0 AS production

USER root

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/

RUN yarn --foline --fronze-lockfile --link-duplicates

COPY . .

RUN yarn build

EXPOSE 3000

CMD [ "node", "dist/main" ]